### PR TITLE
Set correct Gensim licence

### LINKED ISSUE #29: Incorrect licence
I'm not familiar with the Conda process, but its Gensim page https://anaconda.org/conda-forge/gensim lists an incorrect licence, LGPL-3.0:

Screen Shot 2019-05-01 at 12 38 48

Gensim's actual licence is LGPL-2.1.

### PR DESCRIPTION
**Pull request by piskvorky**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes #29. Not sure what the above check boxes are asking for (and no time / interest in investigating); I only fixed the incorrect licence as per #29.

### CODE REVIEW

**Comment by souravsingh** [comment]
LGTM. I would wait for tests to pass before merging it in.

**Comment by menshikh-iv** [comment]
PR doesn't look good
1. The build number isn't bumped
2. Re-render not called (should be called **after** all changes applied)

**Comment by souravsingh** [comment]
Rerender is not needed to call for a small PR like this. I normally call it when there is a version update. As for the build bump, it needs to be done for the PR.

**Comment by souravsingh** [comment]
The PR is currently failing a test for translation matrix. Maybe a sporadic failure?

**Comment by souravsingh** [comment]
@conda-forge-admin, please rerender

**Comment by menshikh-iv** [comment]
@souravsingh  yes, this is "blinking test", sometimes it failed.

**Comment by souravsingh** [comment]
Should be good to merge after tests pass.

**Pull request merged**
