### PR TITLE
Next gensim release

### PR DESCRIPTION
**Pull request by menshikh-iv**
The current branch is a copy of #14 (I need this for having a chance to commit not through UI).

Here
- Branch for next gensim release (because simple bump are not enough, I need changes from conda maintainers too)
- ~~(maybe)~~ Python3.7 support ~~(at least, I'll try)~~ Done!

### CODE REVIEW

**Comment by menshikh-iv** [comment]
Fresh sdist of gensim: [gensim-3.6.0.tar.gz](https://github.com/conda-forge/gensim-feedstock/files/2449277/gensim-3.6.0.tar.gz)

**Comment by souravsingh** [comment]
The tests pass. Merging.

**Comment by menshikh-iv** [comment]
@souravsingh NEVER merge something if you don't fully understand what exactly you do!

This was just adding new python support USING SDIST FROM https://github.com/conda-forge/gensim-feedstock/files/2449277/gensim-3.6.0.tar.gz (not pypi, just check config https://github.com/conda-forge/gensim-feedstock/pull/15/files#diff-e178b687b10a71a3348107ae3154e44cR11)

I killed all CI than runned on master, gensim distribution should be reverted back to PyPI when new gensim will be released (last version have missing files -> test not passed, for this reason, I switch to sdist with fresh version that include all missing files to test it properly). Exactly by this reason this PR shouldn't be merged until next release.

**Comment by souravsingh** [comment]
MY BAD! I saw the PR through my phone and noticed that the tests were ok. It wasn't explicit at a glance that the dist was coming from github rather than PyPI. In any scenario, I have put a PR to revert the changes.

**Pull request merged**
