### PR TITLE
Setup build for MacOSX 

### PR DESCRIPTION
**Pull request by sharanry**
Tries to fix [#1901](https://github.com/RaRe-Technologies/gensim/issues/1901)

### CODE REVIEW

**Comment by souravsingh** [comment]
@sharanry For Gensim to support Mac OS X, you will need to plugin Travis, since conda-forge uses different CI builds for different platforms. If you can figure out how to get Travis working without timeout, that would be awesome.

**Comment by sharanry** [comment]
@souravsingh Thanks for the guidance. 
I saw that you tried to fix this in an earlier test PR, was Travis's timeout the only problem?

**Comment by souravsingh** [comment]
@sharanry Indeed. The Travis times out when running the doc2vec tests.

**Comment by sharanry** [comment]
@souravsingh If resource constraints are cause of the time out, [this](https://docs.travis-ci.com/user/customizing-the-build/#Limiting-Concurrent-Jobs) might be the solution.

**Comment by souravsingh** [comment]
Limit Concurrent Jobs is off for the conda-forge builds.

**Comment by sharanry** [comment]
> Limit Concurrent Jobs is off for the conda-forge builds.

Shouldn't it be tuned on and fixed to 1?

**Comment by souravsingh** [comment]
It is not recommended to edit the Travis YAML files

**Comment by souravsingh** [comment]
The builds are failing for Appveyor and Travis. I would suggest to close and reopen again to restart the CI services.

**Comment by menshikh-iv** [comment]
Hi guys @sharanry  @souravsingh, how is going? What's a problem right now?

**Comment by menshikh-iv** [comment]
@sharanry changed permissions of some files looks very suspicious, why this needed?

**Comment by sharanry** [comment]
> changed permissions of some files looks very suspicious, why this needed?

This was done automatically by conda-smithy, however i manually removed those changes now

**Comment by menshikh-iv** [comment]
@sahmed95 some tips for you: 
- try to run MacOSX with the different testing system (default unittest or pytest).
- check that file compiled correctly (looks OK in logs, but better to manually check it)

**Comment by isuruf** [comment]
If a test timeouts, then you can disable that test by giving `--exclude REGEX` to nosetests.

**Comment by sharanry** [comment]
`Test doc2vec parallel training` is the one taking too long in macos

**Comment by souravsingh** [comment]
@sharanry Yup, that's the one that causes the timeout. And we cannot skip it since it is an important test.

**Comment by sharanry** [comment]
> @sharanry Yup, that's the one that causes the timeout. And we cannot skip it since it is an important test.

Trying to run tests using pytest on travis ci

**Comment by souravsingh** [comment]
There is a mistake in the pytest command.

**Comment by menshikh-iv** [comment]
@sharanry this is really important feature for gensim, please focus on it

**Comment by gyanesh-m** [comment]
@sharanry @souravsingh  Hi, I would also like to help. Travis-ci log for py3.5 and py3.6 failed with error "loader for pytest cannot handle py.test".  It looks like a similar problem as [here](https://github.com/benoitc/gunicorn/issues/440), have a look.

**Comment by menshikh-iv** [comment]
outdated, closing

**Pull request closed without merging**
