### PR TITLE
add dataclasses dependency for version 4.0

### PR DESCRIPTION
**Pull request by izahn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by izahn** [comment]
@conda-forge-admin, please restart ci

**Comment by izahn** [comment]
I'm not 100% sure what is going on with the Travis CI failures, but there are no error messages in the logs. I think this can be merged!

**Comment by mpenkov** [comment]
I had a look at travis, and restarted the failed jobs. There seems to be a genuine problem there with Py3.6. Can you please have a look?

https://travis-ci.com/github/conda-forge/gensim-feedstock/jobs/495248374

```
ModuleNotFoundError: No module named 'dataclasses'

Tests failed for gensim-4.0.0-py36hdee431b_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken

WARNING:conda_build.build:Tests failed for gensim-4.0.0-py36hdee431b_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken

WARNING conda_build.build:tests_failed(2955): Tests failed for gensim-4.0.0-py36hdee431b_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken

TESTS FAILED: gensim-4.0.0-py36hdee431b_0.tar.bz2
```

**Comment by izahn** [comment]
It looks like https://travis-ci.com/github/conda-forge/gensim-feedstock/jobs/495248374 is from https://github.com/conda-forge/gensim-feedstock/pull/58, not this one (https://github.com/conda-forge/gensim-feedstock/pull/57). The only test that hasn't passed for this PR is https://travis-ci.com/github/conda-forge/gensim-feedstock/jobs/495239098 and it doesn't have an error, it just weirdly ends at `Verifying transaction: ...working... `

I think Travis has some issues, but this PR should be good.

**Comment by mpenkov** [comment]
I restarted the failed build and it worked. Thanks again!

**Pull request merged**
